### ISSUE TITLE
Conda packaging: freud dependency not pulling in cython?

### ISSUE THREAD

**Issue by jennyfothergill** [conda-forge/freud-feedstock#46]
### Comment:

I'm [trying to add package that depends on freud to conda-forge](https://github.com/conda-forge/staged-recipes/pull/18608), but when I add freud as a dependency in my meta.yaml, it doesn't automatically pull in cython--is this expected behavior? Am I doing something wrong?

**Comment by bdice** [comment]
Hi @jennyfothergill! Cython is a build-time dependency for freud, but not a runtime dependency. Build time dependencies like cython and scikit-build are only needed to compile the package. Users installing freud only get the “run” dependencies listed here:
https://github.com/conda-forge/freud-feedstock/blob/29736ca183a61d1e2ce07f243d0a752c3cb3ff1f/recipe/meta.yaml#L37-L43

**Comment by bdice** [comment]
@jennyfothergill I'm not exactly sure what caused the error you saw:
```
+ pip check
freud-analysis 2.8.0 requires cython, which is not installed.
```
I'll try to reproduce.

**Comment by bdice** [comment]
I think I see the issue. freud has this line, which is likely the culprit:
https://github.com/glotzerlab/freud/blob/f936dcb7daede4c0780a433d96c0f907a780a330/setup.py#L88

`cython` is listed in `install_requires`, which is supposed to list runtime requirements for the package. However, cython isn't a _runtime_ requirement. Before freud transitioned to scikit-build, we required Cython in `setup.py`. This no longer makes sense because we have pyproject.toml to specify the build time requirements: https://github.com/glotzerlab/freud/blob/f936dcb7daede4c0780a433d96c0f907a780a330/pyproject.toml#L1-L2

This is a bug in freud and I'll file a patch. It is not a bug in the conda-forge feedstock (the package needs to be updated to have build/run requirements that are more like the conda-forge feedstock). Thanks for the catch!

In the meantime, I would disable the `pip check` test for the new `cmeutils` recipe. You'll be able to get the staged recipe approved without that, and you can add it back later if you wish, after we fix freud.

**Comment by bdice** [comment]
To clarify: both cmeutils and freud will run correctly even without removing this extraneous runtime requirement on `cython`. However, `pip check` will fail because freud is missing an (unnecessary) runtime requirement when installed via conda-forge.

**Comment by jennyfothergill** [comment]
That was amazingly fast and helpful!! 🙌 thank you!
